FROM haskell:9.4.2-buster

RUN stack config set system-ghc --global true
RUN stack config install-ghc --global false

# RUN stack install hlint
# RUN stack install floskell
# RUN stack install haskell-language-server
# RUN stack install ghci


